[build]
builder = "NIXPACKS"
buildCommand = "cd intellitutor && npm install && npm run build"

[deploy]
startCommand = "cd intellitutor && npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_VERSION = "22"
